=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DaytonaToolboxApiClient::InterpreterContext
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DaytonaToolboxApiClient::InterpreterContext do
  let(:instance) { DaytonaToolboxApiClient::InterpreterContext.new }

  describe 'test an instance of InterpreterContext' do
    it 'should create an instance of InterpreterContext' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(DaytonaToolboxApiClient::InterpreterContext)
    end
  end

  describe 'test attribute "active"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cwd"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
