=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DaytonaToolboxApiClient::LspCompletionParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DaytonaToolboxApiClient::LspCompletionParams do
  let(:instance) { DaytonaToolboxApiClient::LspCompletionParams.new }

  describe 'test an instance of LspCompletionParams' do
    it 'should create an instance of LspCompletionParams' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(DaytonaToolboxApiClient::LspCompletionParams)
    end
  end

  describe 'test attribute "context"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "language_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "path_to_project"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "position"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "uri"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
