# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.api.port_api import PortApi


class TestPortApi(unittest.TestCase):
    """PortApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortApi()

    def tearDown(self) -> None:
        pass

    def test_get_ports(self) -> None:
        """Test case for get_ports

        Get active ports
        """
        pass

    def test_is_port_in_use(self) -> None:
        """Test case for is_port_in_use

        Check if port is in use
        """
        pass


if __name__ == '__main__':
    unittest.main()
