# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.models.is_port_in_use_response import IsPortInUseResponse

class TestIsPortInUseResponse(unittest.TestCase):
    """IsPortInUseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsPortInUseResponse:
        """Test IsPortInUseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsPortInUseResponse`
        """
        model = IsPortInUseResponse()
        if include_optional:
            return IsPortInUseResponse(
                is_in_use = True
            )
        else:
            return IsPortInUseResponse(
        )
        """

    def testIsPortInUseResponse(self):
        """Test IsPortInUseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
