# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.models.session_execute_response import SessionExecuteResponse

class TestSessionExecuteResponse(unittest.TestCase):
    """SessionExecuteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionExecuteResponse:
        """Test SessionExecuteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionExecuteResponse`
        """
        model = SessionExecuteResponse()
        if include_optional:
            return SessionExecuteResponse(
                cmd_id = '',
                exit_code = 56,
                output = '',
                stderr = '',
                stdout = ''
            )
        else:
            return SessionExecuteResponse(
                cmd_id = '',
        )
        """

    def testSessionExecuteResponse(self):
        """Test SessionExecuteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
