# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.models.list_recordings_response import ListRecordingsResponse

class TestListRecordingsResponse(unittest.TestCase):
    """ListRecordingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRecordingsResponse:
        """Test ListRecordingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRecordingsResponse`
        """
        model = ListRecordingsResponse()
        if include_optional:
            return ListRecordingsResponse(
                recordings = [
                    daytona_toolbox_api_client.models.recording.Recording(
                        duration_seconds = 1.337, 
                        end_time = '', 
                        file_name = '', 
                        file_path = '', 
                        id = '', 
                        size_bytes = 56, 
                        start_time = '', 
                        status = '', )
                    ]
            )
        else:
            return ListRecordingsResponse(
                recordings = [
                    daytona_toolbox_api_client.models.recording.Recording(
                        duration_seconds = 1.337, 
                        end_time = '', 
                        file_name = '', 
                        file_path = '', 
                        id = '', 
                        size_bytes = 56, 
                        start_time = '', 
                        status = '', )
                    ],
        )
        """

    def testListRecordingsResponse(self):
        """Test ListRecordingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
