# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.models.pty_list_response import PtyListResponse

class TestPtyListResponse(unittest.TestCase):
    """PtyListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PtyListResponse:
        """Test PtyListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PtyListResponse`
        """
        model = PtyListResponse()
        if include_optional:
            return PtyListResponse(
                sessions = [
                    daytona_toolbox_api_client.models.pty_session_info.PtySessionInfo(
                        active = True, 
                        cols = 56, 
                        created_at = '', 
                        cwd = '', 
                        envs = {
                            'key' : ''
                            }, 
                        id = '', 
                        lazy_start = True, 
                        rows = 56, )
                    ]
            )
        else:
            return PtyListResponse(
                sessions = [
                    daytona_toolbox_api_client.models.pty_session_info.PtySessionInfo(
                        active = True, 
                        cols = 56, 
                        created_at = '', 
                        cwd = '', 
                        envs = {
                            'key' : ''
                            }, 
                        id = '', 
                        lazy_start = True, 
                        rows = 56, )
                    ],
        )
        """

    def testPtyListResponse(self):
        """Test PtyListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
