# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.api.computer_use_api import ComputerUseApi


class TestComputerUseApi(unittest.TestCase):
    """ComputerUseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComputerUseApi()

    def tearDown(self) -> None:
        pass

    def test_click(self) -> None:
        """Test case for click

        Click mouse button
        """
        pass

    def test_delete_recording(self) -> None:
        """Test case for delete_recording

        Delete a recording
        """
        pass

    def test_download_recording(self) -> None:
        """Test case for download_recording

        Download a recording
        """
        pass

    def test_drag(self) -> None:
        """Test case for drag

        Drag mouse
        """
        pass

    def test_get_computer_use_status(self) -> None:
        """Test case for get_computer_use_status

        Get computer use process status
        """
        pass

    def test_get_computer_use_system_status(self) -> None:
        """Test case for get_computer_use_system_status

        Get computer use status
        """
        pass

    def test_get_display_info(self) -> None:
        """Test case for get_display_info

        Get display information
        """
        pass

    def test_get_mouse_position(self) -> None:
        """Test case for get_mouse_position

        Get mouse position
        """
        pass

    def test_get_process_errors(self) -> None:
        """Test case for get_process_errors

        Get process errors
        """
        pass

    def test_get_process_logs(self) -> None:
        """Test case for get_process_logs

        Get process logs
        """
        pass

    def test_get_process_status(self) -> None:
        """Test case for get_process_status

        Get specific process status
        """
        pass

    def test_get_recording(self) -> None:
        """Test case for get_recording

        Get recording details
        """
        pass

    def test_get_windows(self) -> None:
        """Test case for get_windows

        Get windows information
        """
        pass

    def test_list_recordings(self) -> None:
        """Test case for list_recordings

        List all recordings
        """
        pass

    def test_move_mouse(self) -> None:
        """Test case for move_mouse

        Move mouse cursor
        """
        pass

    def test_press_hotkey(self) -> None:
        """Test case for press_hotkey

        Press hotkey
        """
        pass

    def test_press_key(self) -> None:
        """Test case for press_key

        Press key
        """
        pass

    def test_restart_process(self) -> None:
        """Test case for restart_process

        Restart specific process
        """
        pass

    def test_scroll(self) -> None:
        """Test case for scroll

        Scroll mouse wheel
        """
        pass

    def test_start_computer_use(self) -> None:
        """Test case for start_computer_use

        Start computer use processes
        """
        pass

    def test_start_recording(self) -> None:
        """Test case for start_recording

        Start a new recording
        """
        pass

    def test_stop_computer_use(self) -> None:
        """Test case for stop_computer_use

        Stop computer use processes
        """
        pass

    def test_stop_recording(self) -> None:
        """Test case for stop_recording

        Stop a recording
        """
        pass

    def test_take_compressed_region_screenshot(self) -> None:
        """Test case for take_compressed_region_screenshot

        Take a compressed region screenshot
        """
        pass

    def test_take_compressed_screenshot(self) -> None:
        """Test case for take_compressed_screenshot

        Take a compressed screenshot
        """
        pass

    def test_take_region_screenshot(self) -> None:
        """Test case for take_region_screenshot

        Take a region screenshot
        """
        pass

    def test_take_screenshot(self) -> None:
        """Test case for take_screenshot

        Take a screenshot
        """
        pass

    def test_type_text(self) -> None:
        """Test case for type_text

        Type text
        """
        pass


if __name__ == '__main__':
    unittest.main()
