# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.api.lsp_api import LspApi


class TestLspApi(unittest.TestCase):
    """LspApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LspApi()

    def tearDown(self) -> None:
        pass

    def test_completions(self) -> None:
        """Test case for completions

        Get code completions
        """
        pass

    def test_did_close(self) -> None:
        """Test case for did_close

        Notify document closed
        """
        pass

    def test_did_open(self) -> None:
        """Test case for did_open

        Notify document opened
        """
        pass

    def test_document_symbols(self) -> None:
        """Test case for document_symbols

        Get document symbols
        """
        pass

    def test_start(self) -> None:
        """Test case for start

        Start LSP server
        """
        pass

    def test_stop(self) -> None:
        """Test case for stop

        Stop LSP server
        """
        pass

    def test_workspace_symbols(self) -> None:
        """Test case for workspace_symbols

        Get workspace symbols
        """
        pass


if __name__ == '__main__':
    unittest.main()
