# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client.models.recording import Recording

class TestRecording(unittest.TestCase):
    """Recording unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Recording:
        """Test Recording
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Recording`
        """
        model = Recording()
        if include_optional:
            return Recording(
                duration_seconds = 1.337,
                end_time = '',
                file_name = '',
                file_path = '',
                id = '',
                size_bytes = 56,
                start_time = '',
                status = ''
            )
        else:
            return Recording(
                file_name = '',
                file_path = '',
                id = '',
                start_time = '',
                status = '',
        )
        """

    def testRecording(self):
        """Test Recording"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
