/*
Daytona Toolbox API

Daytona Toolbox API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PkgToolboxGitGitDeleteBranchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PkgToolboxGitGitDeleteBranchRequest{}

// PkgToolboxGitGitDeleteBranchRequest struct for PkgToolboxGitGitDeleteBranchRequest
type PkgToolboxGitGitDeleteBranchRequest struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

type _PkgToolboxGitGitDeleteBranchRequest PkgToolboxGitGitDeleteBranchRequest

// NewPkgToolboxGitGitDeleteBranchRequest instantiates a new PkgToolboxGitGitDeleteBranchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkgToolboxGitGitDeleteBranchRequest(name string, path string) *PkgToolboxGitGitDeleteBranchRequest {
	this := PkgToolboxGitGitDeleteBranchRequest{}
	this.Name = name
	this.Path = path
	return &this
}

// NewPkgToolboxGitGitDeleteBranchRequestWithDefaults instantiates a new PkgToolboxGitGitDeleteBranchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkgToolboxGitGitDeleteBranchRequestWithDefaults() *PkgToolboxGitGitDeleteBranchRequest {
	this := PkgToolboxGitGitDeleteBranchRequest{}
	return &this
}

// GetName returns the Name field value
func (o *PkgToolboxGitGitDeleteBranchRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PkgToolboxGitGitDeleteBranchRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PkgToolboxGitGitDeleteBranchRequest) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *PkgToolboxGitGitDeleteBranchRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *PkgToolboxGitGitDeleteBranchRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *PkgToolboxGitGitDeleteBranchRequest) SetPath(v string) {
	o.Path = v
}

func (o PkgToolboxGitGitDeleteBranchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PkgToolboxGitGitDeleteBranchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *PkgToolboxGitGitDeleteBranchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPkgToolboxGitGitDeleteBranchRequest := _PkgToolboxGitGitDeleteBranchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPkgToolboxGitGitDeleteBranchRequest)

	if err != nil {
		return err
	}

	*o = PkgToolboxGitGitDeleteBranchRequest(varPkgToolboxGitGitDeleteBranchRequest)

	return err
}

type NullablePkgToolboxGitGitDeleteBranchRequest struct {
	value *PkgToolboxGitGitDeleteBranchRequest
	isSet bool
}

func (v NullablePkgToolboxGitGitDeleteBranchRequest) Get() *PkgToolboxGitGitDeleteBranchRequest {
	return v.value
}

func (v *NullablePkgToolboxGitGitDeleteBranchRequest) Set(val *PkgToolboxGitGitDeleteBranchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePkgToolboxGitGitDeleteBranchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePkgToolboxGitGitDeleteBranchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkgToolboxGitGitDeleteBranchRequest(val *PkgToolboxGitGitDeleteBranchRequest) *NullablePkgToolboxGitGitDeleteBranchRequest {
	return &NullablePkgToolboxGitGitDeleteBranchRequest{value: val, isSet: true}
}

func (v NullablePkgToolboxGitGitDeleteBranchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkgToolboxGitGitDeleteBranchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


