=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DaytonaToolboxApiClient::GitApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GitApi' do
  before do
    # run before each test
    @api_instance = DaytonaToolboxApiClient::GitApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GitApi' do
    it 'should create an instance of GitApi' do
      expect(@api_instance).to be_instance_of(DaytonaToolboxApiClient::GitApi)
    end
  end

  # unit tests for add_files
  # Add files to Git staging
  # Add files to the Git staging area
  # @param request Add files request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_files test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for checkout_branch
  # Checkout branch or commit
  # Switch to a different branch or commit in the Git repository
  # @param request Checkout request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'checkout_branch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for clone_repository
  # Clone a Git repository
  # Clone a Git repository to the specified path
  # @param request Clone repository request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'clone_repository test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for commit_changes
  # Commit changes
  # Commit staged changes to the Git repository
  # @param request Commit request
  # @param [Hash] opts the optional parameters
  # @return [GitCommitResponse]
  describe 'commit_changes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_branch
  # Create a new branch
  # Create a new branch in the Git repository
  # @param request Create branch request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_branch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_branch
  # Delete a branch
  # Delete a branch from the Git repository
  # @param request Delete branch request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_branch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_commit_history
  # Get commit history
  # Get the commit history of the Git repository
  # @param path Repository path
  # @param [Hash] opts the optional parameters
  # @return [Array<GitCommitInfo>]
  describe 'get_commit_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_status
  # Get Git status
  # Get the Git status of the repository at the specified path
  # @param path Repository path
  # @param [Hash] opts the optional parameters
  # @return [GitStatus]
  describe 'get_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_branches
  # List branches
  # Get a list of all branches in the Git repository
  # @param path Repository path
  # @param [Hash] opts the optional parameters
  # @return [ListBranchResponse]
  describe 'list_branches test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pull_changes
  # Pull changes from remote
  # Pull changes from the remote Git repository
  # @param request Pull request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'pull_changes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for push_changes
  # Push changes to remote
  # Push local changes to the remote Git repository
  # @param request Push request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'push_changes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
