=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DaytonaToolboxApiClient::InfoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InfoApi' do
  before do
    # run before each test
    @api_instance = DaytonaToolboxApiClient::InfoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InfoApi' do
    it 'should create an instance of InfoApi' do
      expect(@api_instance).to be_instance_of(DaytonaToolboxApiClient::InfoApi)
    end
  end

  # unit tests for get_user_home_dir
  # Get user home directory
  # Get the current user home directory path.
  # @param [Hash] opts the optional parameters
  # @return [UserHomeDirResponse]
  describe 'get_user_home_dir test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_version
  # Get version
  # Get the current daemon version
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, String>]
  describe 'get_version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_work_dir
  # Get working directory
  # Get the current working directory path. This is default directory used for running commands.
  # @param [Hash] opts the optional parameters
  # @return [WorkDirResponse]
  describe 'get_work_dir test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
