=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DaytonaToolboxApiClient::LspApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LspApi' do
  before do
    # run before each test
    @api_instance = DaytonaToolboxApiClient::LspApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LspApi' do
    it 'should create an instance of LspApi' do
      expect(@api_instance).to be_instance_of(DaytonaToolboxApiClient::LspApi)
    end
  end

  # unit tests for completions
  # Get code completions
  # Get code completion suggestions from the LSP server
  # @param request Completion request
  # @param [Hash] opts the optional parameters
  # @return [CompletionList]
  describe 'completions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for did_close
  # Notify document closed
  # Notify the LSP server that a document has been closed
  # @param request Document request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_close test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for did_open
  # Notify document opened
  # Notify the LSP server that a document has been opened
  # @param request Document request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_open test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for document_symbols
  # Get document symbols
  # Get symbols (functions, classes, etc.) from a document
  # @param language_id Language ID (e.g., python, typescript)
  # @param path_to_project Path to project
  # @param uri Document URI
  # @param [Hash] opts the optional parameters
  # @return [Array<LspSymbol>]
  describe 'document_symbols test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for start
  # Start LSP server
  # Start a Language Server Protocol server for the specified language
  # @param request LSP server request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'start test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stop
  # Stop LSP server
  # Stop a Language Server Protocol server
  # @param request LSP server request
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'stop test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_symbols
  # Get workspace symbols
  # Search for symbols across the entire workspace
  # @param query Search query
  # @param language_id Language ID (e.g., python, typescript)
  # @param path_to_project Path to project
  # @param [Hash] opts the optional parameters
  # @return [Array<LspSymbol>]
  describe 'workspace_symbols test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
