=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DaytonaToolboxApiClient::PortApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PortApi' do
  before do
    # run before each test
    @api_instance = DaytonaToolboxApiClient::PortApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PortApi' do
    it 'should create an instance of PortApi' do
      expect(@api_instance).to be_instance_of(DaytonaToolboxApiClient::PortApi)
    end
  end

  # unit tests for get_ports
  # Get active ports
  # Get a list of all currently active ports
  # @param [Hash] opts the optional parameters
  # @return [PortList]
  describe 'get_ports test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for is_port_in_use
  # Check if port is in use
  # Check if a specific port is currently in use
  # @param port Port number (3000-9999)
  # @param [Hash] opts the optional parameters
  # @return [IsPortInUseResponse]
  describe 'is_port_in_use test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
