=begin
#Daytona Toolbox API

#Daytona Toolbox API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DaytonaToolboxApiClient::ServerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServerApi' do
  before do
    # run before each test
    @api_instance = DaytonaToolboxApiClient::ServerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServerApi' do
    it 'should create an instance of ServerApi' do
      expect(@api_instance).to be_instance_of(DaytonaToolboxApiClient::ServerApi)
    end
  end

  # unit tests for initialize
  # Initialize toolbox server
  # Set the auth token and initialize telemetry for the toolbox server
  # @param request Initialization request
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, String>]
  describe 'initialize test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
