# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.process_api import ProcessApi


class TestProcessApi(unittest.IsolatedAsyncioTestCase):
    """ProcessApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProcessApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_code_run(self) -> None:
        """Test case for code_run

        Execute code
        """
        pass

    async def test_connect_pty_session(self) -> None:
        """Test case for connect_pty_session

        Connect to PTY session via WebSocket
        """
        pass

    async def test_create_pty_session(self) -> None:
        """Test case for create_pty_session

        Create a new PTY session
        """
        pass

    async def test_create_session(self) -> None:
        """Test case for create_session

        Create a new session
        """
        pass

    async def test_delete_pty_session(self) -> None:
        """Test case for delete_pty_session

        Delete a PTY session
        """
        pass

    async def test_delete_session(self) -> None:
        """Test case for delete_session

        Delete a session
        """
        pass

    async def test_execute_command(self) -> None:
        """Test case for execute_command

        Execute a command
        """
        pass

    async def test_get_entrypoint_logs(self) -> None:
        """Test case for get_entrypoint_logs

        Get entrypoint logs
        """
        pass

    async def test_get_entrypoint_session(self) -> None:
        """Test case for get_entrypoint_session

        Get entrypoint session details
        """
        pass

    async def test_get_pty_session(self) -> None:
        """Test case for get_pty_session

        Get PTY session information
        """
        pass

    async def test_get_session(self) -> None:
        """Test case for get_session

        Get session details
        """
        pass

    async def test_get_session_command(self) -> None:
        """Test case for get_session_command

        Get session command details
        """
        pass

    async def test_get_session_command_logs(self) -> None:
        """Test case for get_session_command_logs

        Get session command logs
        """
        pass

    async def test_list_pty_sessions(self) -> None:
        """Test case for list_pty_sessions

        List all PTY sessions
        """
        pass

    async def test_list_sessions(self) -> None:
        """Test case for list_sessions

        List all sessions
        """
        pass

    async def test_resize_pty_session(self) -> None:
        """Test case for resize_pty_session

        Resize a PTY session
        """
        pass

    async def test_send_input(self) -> None:
        """Test case for send_input

        Send input to command
        """
        pass

    async def test_session_execute_command(self) -> None:
        """Test case for session_execute_command

        Execute command in session
        """
        pass


if __name__ == '__main__':
    unittest.main()
