# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.file_system_api import FileSystemApi


class TestFileSystemApi(unittest.IsolatedAsyncioTestCase):
    """FileSystemApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FileSystemApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_folder(self) -> None:
        """Test case for create_folder

        Create a folder
        """
        pass

    async def test_delete_file(self) -> None:
        """Test case for delete_file

        Delete a file or directory
        """
        pass

    async def test_download_file(self) -> None:
        """Test case for download_file

        Download a file
        """
        pass

    async def test_download_files(self) -> None:
        """Test case for download_files

        Download multiple files
        """
        pass

    async def test_find_in_files(self) -> None:
        """Test case for find_in_files

        Find text in files
        """
        pass

    async def test_get_file_info(self) -> None:
        """Test case for get_file_info

        Get file information
        """
        pass

    async def test_list_files(self) -> None:
        """Test case for list_files

        List files and directories
        """
        pass

    async def test_move_file(self) -> None:
        """Test case for move_file

        Move or rename file/directory
        """
        pass

    async def test_replace_in_files(self) -> None:
        """Test case for replace_in_files

        Replace text in files
        """
        pass

    async def test_search_files(self) -> None:
        """Test case for search_files

        Search files by pattern
        """
        pass

    async def test_set_file_permissions(self) -> None:
        """Test case for set_file_permissions

        Set file permissions
        """
        pass

    async def test_upload_file(self) -> None:
        """Test case for upload_file

        Upload a file
        """
        pass

    async def test_upload_files(self) -> None:
        """Test case for upload_files

        Upload multiple files
        """
        pass


if __name__ == '__main__':
    unittest.main()
