# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.models.code_run_response import CodeRunResponse

class TestCodeRunResponse(unittest.TestCase):
    """CodeRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodeRunResponse:
        """Test CodeRunResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodeRunResponse`
        """
        model = CodeRunResponse()
        if include_optional:
            return CodeRunResponse(
                artifacts = daytona_toolbox_api_client_async.models.code_run_artifacts.CodeRunArtifacts(
                    charts = [
                        { }
                        ], ),
                exit_code = 56,
                result = ''
            )
        else:
            return CodeRunResponse(
        )
        """

    def testCodeRunResponse(self):
        """Test CodeRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
