# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.models.process_status import ProcessStatus

class TestProcessStatus(unittest.TestCase):
    """ProcessStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessStatus:
        """Test ProcessStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessStatus`
        """
        model = ProcessStatus()
        if include_optional:
            return ProcessStatus(
                auto_restart = True,
                pid = 56,
                priority = 56,
                running = True
            )
        else:
            return ProcessStatus(
        )
        """

    def testProcessStatus(self):
        """Test ProcessStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
