# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.info_api import InfoApi


class TestInfoApi(unittest.IsolatedAsyncioTestCase):
    """InfoApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InfoApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_user_home_dir(self) -> None:
        """Test case for get_user_home_dir

        Get user home directory
        """
        pass

    async def test_get_version(self) -> None:
        """Test case for get_version

        Get version
        """
        pass

    async def test_get_work_dir(self) -> None:
        """Test case for get_work_dir

        Get working directory
        """
        pass


if __name__ == '__main__':
    unittest.main()
