# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.git_api import GitApi


class TestGitApi(unittest.IsolatedAsyncioTestCase):
    """GitApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = GitApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_files(self) -> None:
        """Test case for add_files

        Add files to Git staging
        """
        pass

    async def test_checkout_branch(self) -> None:
        """Test case for checkout_branch

        Checkout branch or commit
        """
        pass

    async def test_clone_repository(self) -> None:
        """Test case for clone_repository

        Clone a Git repository
        """
        pass

    async def test_commit_changes(self) -> None:
        """Test case for commit_changes

        Commit changes
        """
        pass

    async def test_create_branch(self) -> None:
        """Test case for create_branch

        Create a new branch
        """
        pass

    async def test_delete_branch(self) -> None:
        """Test case for delete_branch

        Delete a branch
        """
        pass

    async def test_get_commit_history(self) -> None:
        """Test case for get_commit_history

        Get commit history
        """
        pass

    async def test_get_status(self) -> None:
        """Test case for get_status

        Get Git status
        """
        pass

    async def test_list_branches(self) -> None:
        """Test case for list_branches

        List branches
        """
        pass

    async def test_pull_changes(self) -> None:
        """Test case for pull_changes

        Pull changes from remote
        """
        pass

    async def test_push_changes(self) -> None:
        """Test case for push_changes

        Push changes to remote
        """
        pass


if __name__ == '__main__':
    unittest.main()
