# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.interpreter_api import InterpreterApi


class TestInterpreterApi(unittest.IsolatedAsyncioTestCase):
    """InterpreterApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InterpreterApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_interpreter_context(self) -> None:
        """Test case for create_interpreter_context

        Create a new interpreter context
        """
        pass

    async def test_delete_interpreter_context(self) -> None:
        """Test case for delete_interpreter_context

        Delete an interpreter context
        """
        pass

    async def test_execute_interpreter_code(self) -> None:
        """Test case for execute_interpreter_code

        Execute code in an interpreter context
        """
        pass

    async def test_list_interpreter_contexts(self) -> None:
        """Test case for list_interpreter_contexts

        List all user-created interpreter contexts
        """
        pass


if __name__ == '__main__':
    unittest.main()
