# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.api.lsp_api import LspApi


class TestLspApi(unittest.IsolatedAsyncioTestCase):
    """LspApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LspApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_completions(self) -> None:
        """Test case for completions

        Get code completions
        """
        pass

    async def test_did_close(self) -> None:
        """Test case for did_close

        Notify document closed
        """
        pass

    async def test_did_open(self) -> None:
        """Test case for did_open

        Notify document opened
        """
        pass

    async def test_document_symbols(self) -> None:
        """Test case for document_symbols

        Get document symbols
        """
        pass

    async def test_start(self) -> None:
        """Test case for start

        Start LSP server
        """
        pass

    async def test_stop(self) -> None:
        """Test case for stop

        Stop LSP server
        """
        pass

    async def test_workspace_symbols(self) -> None:
        """Test case for workspace_symbols

        Get workspace symbols
        """
        pass


if __name__ == '__main__':
    unittest.main()
