# coding: utf-8

"""
    Daytona Toolbox API

    Daytona Toolbox API

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from daytona_toolbox_api_client_async.models.windows_response import WindowsResponse

class TestWindowsResponse(unittest.TestCase):
    """WindowsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WindowsResponse:
        """Test WindowsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WindowsResponse`
        """
        model = WindowsResponse()
        if include_optional:
            return WindowsResponse(
                windows = [
                    daytona_toolbox_api_client_async.models.window_info.WindowInfo(
                        height = 56, 
                        id = 56, 
                        is_active = True, 
                        title = '', 
                        width = 56, 
                        x = 56, 
                        y = 56, )
                    ]
            )
        else:
            return WindowsResponse(
        )
        """

    def testWindowsResponse(self):
        """Test WindowsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
